import type { CardType, Faction, Rarity } from '@/data/cards'
import { abyssian, lyonar, magmar, neutral, songhai, vanar, vetruvian } from './utils'

export interface ScrapedCard {
  id: number
  name: string
  faction: Faction
  type: CardType
  cost: number
  rarity: Rarity
  spriteName?: string
}

export const lyonarCardData: ScrapedCard[] = [
  lyonar(60, 'Argeon Highmayne', 0, 'General', 'basic', 'f1_general'),
  lyonar(76, 'Brome Warcrest', 0, 'General', 'basic', 'f1_3rdgeneral'),
  lyonar(75, "Zir'An Sunforge", 0, 'General', 'basic', 'f1_altgeneral'),
  lyonar(20414, 'Beam Shock', 0, 'Spell', 'common', 'icon_f1_d2_beamshock'),
  lyonar(20410, 'Lionheart Blessing', 0, 'Spell', 'rare', 'icon_f1_d2_lionheartblessing'),
  lyonar(30102, 'Sunstone Bracers', 0, 'Artifact', 'basic', 'artifact_f1_d2_sunstonebracers'),
  lyonar(20417, 'Aegis Barrier', 1, 'Spell', 'legendary', 'icon_f1_d2_aegisbarrier'),
  lyonar(20418, 'Aerial Rift', 1, 'Spell', 'epic', 'icon_f1_d2_aerial_rift'),
  lyonar(20406, 'Auryn Nexus', 1, 'Spell', 'common', 'icon_f1_d2_aurynnexus'),
  lyonar(20419, 'Magnetize', 1, 'Spell', 'rare', 'icon_f1_d2_magnetize'),
  lyonar(61, 'Silverguard Squire', 1, 'Minion', 'common', 'f1_silverguardsquire'),
  lyonar(20404, 'Sundrop Elixir', 1, 'Spell', 'common', 'icon_f1_d2_sundropelixir'),
  lyonar(20412, 'True Strike', 1, 'Spell', 'basic', 'icon_f1_d2_truestrike'),
  lyonar(73, 'Azurite Lion', 2, 'Minion', 'common', 'f1_azuritelion'),
  lyonar(20407, 'Lasting Judgement', 2, 'Spell', 'rare', 'icon_f1_d2_lastingjudgement'),
  lyonar(68, 'Lightchaser', 2, 'Minion', 'common', 'f1_caster'),
  lyonar(20409, 'Martyrdom', 2, 'Spell', 'basic', 'icon_f1_d2_martydom'),
  lyonar(20411, 'Sun Bloom', 2, 'Spell', 'common', 'icon_f1_d2_sunbloom'),
  lyonar(63, 'Sunstone Templar', 2, 'Minion', 'epic', 'f1_sunstonetemplar'),
  lyonar(20405, 'Tempest', 2, 'Spell', 'basic', 'icon_f1_d2_tempest'),
  lyonar(20408, 'War Surge', 2, 'Spell', 'basic', 'icon_f1_d2_warsurge'),
  lyonar(62, 'Windblade Adept', 2, 'Minion', 'basic', 'f1_melee'),
  lyonar(65, 'Arclyte Sentinel', 3, 'Minion', 'rare', 'f1_special'),
  lyonar(20416, 'Divine Bond', 3, 'Spell', 'basic', 'icon_f1_d2_divinebond'),
  lyonar(64, 'Silverguard Knight', 3, 'Minion', 'basic', 'f1_tank'),
  lyonar(30101, 'Skywind Glaives', 3, 'Artifact', 'epic', 'artifact_f1_d2_skywindglaives'),
  lyonar(30103, 'Arclyte Regalia', 4, 'Artifact', 'legendary', 'artifact_f1_d2_arclyteregalia'),
  lyonar(20420, 'Decimate', 4, 'Spell', 'legendary', 'icon_f1_d2_decimate'),
  lyonar(20415, 'Holy Immolation', 4, 'Spell', 'epic', 'icon_f1_d2_holyimmolation'),
  lyonar(67, 'Lysian Brawler', 4, 'Minion', 'basic', 'f1_silvermanevanguard'),
  lyonar(74, 'Sunriser', 4, 'Minion', 'epic', 'f1_sunriser'),
  lyonar(69, 'Suntide Maiden', 4, 'Minion', 'common', 'f1_support'),
  lyonar(20413, 'Circle of Life', 5, 'Spell', 'epic', 'icon_f1_d2_circleoflife'),
  lyonar(70, 'Ironcliffe Guardian', 5, 'Minion', 'rare', 'f1_ironcliffeguardian'),
  lyonar(66, 'Second Sun', 5, 'Minion', 'rare', 'f1_windbladecommander'),
  lyonar(71, 'Elyx Stormblade', 6, 'Minion', 'legendary', 'f1_elyxstormblade'),
  lyonar(72, "Grandmaster Z'ir", 7, 'Minion', 'legendary', 'f1_grandmasterzir'),
]

export const songhaiCardData: ScrapedCard[] = [
  songhai(161, 'Kaleos Xaan', 0, 'General', 'basic', 'f2_general'),
  songhai(177, 'Reva Eventide', 0, 'General', 'basic', 'f2_altgeneral'),
  songhai(178, 'Shidai Stormblossom', 0, 'General', 'basic', 'f2_3rdgeneral'),
  songhai(20429, 'Inner Focus', 0, 'Spell', 'basic', 'icon_f2_d2_inner_focus'),
  songhai(20434, 'Juxtaposition', 0, 'Spell', 'epic', 'icon_f2_d2_juxtaposition'),
  songhai(20428, 'Mana Vortex', 0, 'Spell', 'rare', 'icon_f2_d2_mana_vortex'),
  songhai(20433, 'Ancestral Divination', 1, 'Spell', 'common', 'icon_f2_d2_ancestralpact'),
  songhai(20435, 'Artifact Defiler', 1, 'Spell', 'common', 'icon_f2_d2_artifact_defiler'),
  songhai(30106, 'Bloodrage Mask', 1, 'Artifact', 'basic', 'artifact_f2_d2_bloodleechmask'),
  songhai(20431, 'Ghost Lightning', 1, 'Spell', 'basic', 'icon_f2_d2_ghost_lightning'),
  songhai(162, 'Heartseeker', 1, 'Minion', 'common', 'f2_caster'),
  songhai(20437, 'Mist Walking', 1, 'Spell', 'rare', 'icon_f2_d2_mistwalking'),
  songhai(20421, 'Saberspine Seal', 1, 'Spell', 'basic', 'icon_f2_d2_saberspineseal'),
  songhai(169, 'Chakri Avatar', 2, 'Minion', 'basic', 'f2_chakriavatar'),
  songhai(20432, 'Deathstrike Seal', 2, 'Spell', 'rare', 'icon_f2_d2_deathstrikeseal'),
  songhai(20426, 'Eight Gates', 2, 'Spell', 'legendary', 'icon_f2_d2_eightgates'),
  songhai(164, 'Kaido Assassin', 2, 'Minion', 'basic', 'f2_melee'),
  songhai(30104, 'Mask of Shadows', 2, 'Artifact', 'legendary', 'artifact_f2_d2_maskofshadows'),
  songhai(20422, 'Mist Dragon Seal', 2, 'Spell', 'common', 'icon_f2_d2_mistdragonseal'),
  songhai(20423, 'Phoenix Fire', 2, 'Spell', 'basic', 'icon_f2_d2_phoenixfire02'),
  songhai(175, 'Tusk Boar', 2, 'Minion', 'legendary', 'f2_special'),
  songhai(171, 'Celestial Phantom', 3, 'Minion', 'rare', 'f2_deathphantom'),
  songhai(30105, 'Cyclone Mask', 3, 'Artifact', 'epic', 'artifact_f2_d2_cyclonemask'),
  songhai(166, 'Gore Horn', 3, 'Minion', 'rare', 'f2_tank'),
  songhai(20438, 'Killing Edge', 3, 'Spell', 'basic', 'icon_f2_d2_killingedge'),
  songhai(176, 'Lantern Fox', 3, 'Minion', 'epic', 'f2_lanternfox'),
  songhai(20430, 'Onyx Bear Seal', 3, 'Spell', 'epic', 'icon_f2_d2_onyxbearseal'),
  songhai(20425, 'Twin Strike', 3, 'Spell', 'common', 'icon_f2_d2_twin_strike'),
  songhai(163, 'Widowmaker', 3, 'Minion', 'basic', 'f2_ranged'),
  songhai(170, 'Four Winds Magus', 4, 'Minion', 'rare', 'f2_mage4winds'),
  songhai(20436, "Heaven's Eclipse", 4, 'Spell', 'legendary', 'icon_f2_d2_heavens_eclipse'),
  songhai(168, 'Jade Monk', 4, 'Minion', 'common', 'f2_ogremonk02'),
  songhai(174, 'Keshrai Fanblade', 4, 'Minion', 'common', 'f2_keshraifanblade'),
  songhai(173, 'Hamon Bladeseeker', 5, 'Minion', 'epic', 'f2_hammonnladeseeker'),
  songhai(165, 'Scarlet Viper', 5, 'Minion', 'common', 'f2_support'),
  songhai(20427, 'Spiral Technique', 7, 'Spell', 'epic', 'icon_f2_d2_spiraltechnique'),
  songhai(172, 'Storm Kage', 7, 'Minion', 'epic', 'f2_stormkage'),
]

export const vetruvianCardData: ScrapedCard[] = [
  vetruvian(281, 'Ciphyron Ascendant', 0, 'General', 'basic', 'f3_3rdgeneral'),
  vetruvian(280, 'Scioness Sajj', 0, 'General', 'basic', 'f3_altgeneral'),
  vetruvian(264, 'Zirix Starstrider', 0, 'General', 'basic', 'f3_general'),
  vetruvian(20455, 'Fountain of Youth', 0, 'Spell', 'rare', 'icon_f3_d2_fountainofyouth'),
  vetruvian(20440, 'Siphon Energy', 0, 'Spell', 'common', 'icon_f3_d2_syphonenergy'),
  vetruvian(20444, 'Auroras Tears', 1, 'Spell', 'epic', 'icon_f3_d2_aurorastear'),
  vetruvian(20442, 'Blindscorch', 1, 'Spell', 'basic', 'icon_f3_d2_blindscorch'),
  vetruvian(20448, "Scion's First Wish", 1, 'Spell', 'basic', 'icon_f3_d2_scionsfirstwish'),
  vetruvian(20454, 'Bone Swarm', 2, 'Spell', 'common', 'icon_f3_d2_boneswarm'),
  vetruvian(20441, 'Cosmic Flesh', 2, 'Spell', 'basic', 'icon_f3_d2_cosmicflesh'),
  vetruvian(268, 'Dunecaster', 2, 'Minion', 'common', 'f3_orbweaver'),
  vetruvian(271, 'Ethereal Obelysk', 2, 'Minion', 'basic', 'f3_obelyskredsand'),
  vetruvian(275, 'Imperial Mechanyst', 2, 'Minion', 'rare', 'f3_palacetrinketeer'),
  vetruvian(269, 'Orb Weaver', 2, 'Minion', 'common', 'f3_dunecaster'),
  vetruvian(270, 'Pyromancer', 2, 'Minion', 'basic', 'f3_pyromancer'),
  vetruvian(20451, "Rasha's Curse", 2, 'Spell', 'epic', 'icon_f3_d2_rashascurse'),
  vetruvian(20447, 'Sand Trap', 2, 'Spell', 'common', 'icon_f3_d2_sandtrap'),
  vetruvian(20449, "Scion's Second Wish", 2, 'Spell', 'basic', 'icon_f3_d2_scionssecondwish'),
  vetruvian(30107, "Staff Of Y'Kir", 2, 'Artifact', 'basic', 'artifact_f3_d2_staffofykir'),
  vetruvian(20443, 'Astral Phasing', 3, 'Spell', 'common', 'icon_f3_d2_astralphasing'),
  vetruvian(272, 'Fireblaze Obelysk', 3, 'Minion', 'rare', 'f3_obelyskgoldenflame'),
  vetruvian(20456, 'Inner Oasis', 3, 'Spell', 'rare', 'icon_f3_d2_inneroasis'),
  vetruvian(278, 'Portal Guardian', 3, 'Minion', 'epic', 'f3_zodiac02'),
  vetruvian(20450, "Scion's Third Wish", 3, 'Spell', 'legendary', 'icon_f3_d2_scionsthirdwish'),
  vetruvian(30108, 'Wildfire Ankh', 3, 'Artifact', 'epic', 'artifact_f3_d2_wildfireankh'),
  vetruvian(273, 'Windstorm Obelysk', 3, 'Minion', 'common', 'f3_obelyskduskwind'),
  vetruvian(20445, 'Entropic Decay', 4, 'Spell', 'basic', 'icon_f3_d2_entropicdecay'),
  vetruvian(30109, 'Hexblade', 4, 'Artifact', 'legendary', 'artifact_f3_d2_hexblade'),
  vetruvian(276, 'Mirage Master', 4, 'Minion', 'epic', 'f3_glassmirage'),
  vetruvian(267, 'Sand Howler', 4, 'Minion', 'rare', 'f3_sandhowler'),
  vetruvian(265, 'Wind Shrike', 4, 'Minion', 'basic', 'f3_windshriek'),
  vetruvian(20453, "Star's Fury", 5, 'Spell', 'epic', 'icon_f3_d2_starsfury'),
  vetruvian(266, 'Starfire Scarab', 5, 'Minion', 'common', 'f3_starfirescarab'),
  vetruvian(277, 'Aymara Healer', 6, 'Minion', 'legendary', 'f3_aymarahealer'),
  vetruvian(20439, 'Dominate Will', 7, 'Spell', 'rare', 'icon_f3_d2_enslave'),
  vetruvian(279, 'Oserix', 7, 'Minion', 'legendary', 'f3_anubis'),
  vetruvian(20446, 'Time Maelstrom', 9, 'Spell', 'legendary', 'icon_f3_d2_maelstrom'),
]

export const abyssianCardData: ScrapedCard[] = [
  abyssian(380, 'Cassyva Soulreaper', 0, 'General', 'basic', 'f4_altgeneral'),
  abyssian(364, 'Lilithe Blightchaser', 0, 'General', 'basic', 'f4_general'),
  abyssian(381, 'Maehv Skinsolder', 0, 'General', 'basic', 'f4_3rdgeneral'),
  abyssian(20465, 'Darkfire Sacrifice', 0, 'Spell', 'rare', 'icon_f4_d2_darkfiresacrifice'),
  abyssian(365, 'Abyssal Crawler', 1, 'Minion', 'basic', 'f4_crawler'),
  abyssian(20469, 'Grasp of Agony', 1, 'Spell', 'common', 'icon_f4_d2_curseofagony'),
  abyssian(30111, 'Horn of the Forsaken', 1, 'Artifact', 'basic', 'artifact_f4_d2_hornofforsaken'),
  abyssian(20461, 'Void Pulse', 1, 'Spell', 'common', 'icon_f4_d2_voidpulse'),
  abyssian(370, 'Blood Siren', 2, 'Minion', 'common', 'f4_siren'),
  abyssian(20473, 'Consuming Rebirth', 2, 'Spell', 'epic', 'icon_f4_d2_consumingrebirth'),
  abyssian(20458, 'Daemonic Lure', 2, 'Spell', 'basic', 'icon_f4_d2_daemoniclure'),
  abyssian(373, 'Darkspine Elemental', 2, 'Minion', 'rare', 'f4_darkspine'),
  abyssian(374, 'Gloomchaser', 2, 'Minion', 'basic', 'f4_gloomchaser'),
  abyssian(20471, 'Soulshatter Pact', 2, 'Spell', 'basic', 'icon_f4_d2_soulshatterpact'),
  abyssian(30112, 'Spectral Blade', 2, 'Artifact', 'epic', 'artifact_f4_d2_spectralblade'),
  abyssian(20462, 'Deathfire Crescendo', 3, 'Spell', 'legendary', 'icon_f4_d2_deathfirecrescendo'),
  abyssian(376, 'Nightsorrow Assassin', 3, 'Minion', 'common', 'f4_nightsorrow'),
  abyssian(20464, 'Rite Of The Undervault', 3, 'Spell', 'epic', 'icon_f4_d2_riteoftheundervault'),
  abyssian(20466, 'Ritual Banishing', 3, 'Spell', 'rare', 'icon_f4_d2_ritualbanishing'),
  abyssian(20470, 'Shadow Reflection', 3, 'Spell', 'common', 'icon_f4_d2_shadowreflection'),
  abyssian(368, 'Shadow Watcher', 3, 'Minion', 'basic', 'f4_engulfingshadow'),
  abyssian(30110, 'Soul Grimoire', 3, 'Artifact', 'legendary', 'artifact_f4_d2_soulgrimwar'),
  abyssian(20457, 'Wraithling Fury', 3, 'Spell', 'epic', 'icon_f4_d2_wraithlingfury'),
  abyssian(20472, 'Wraithling Swarm', 3, 'Spell', 'basic', 'icon_f4_d2_wraithlingswarm'),
  abyssian(366, 'Abyssal Juggernaut', 4, 'Minion', 'common', 'f4_juggernaut'),
  abyssian(369, 'Aphotic Devourer', 4, 'Minion', 'common', 'f4_daemondeep'),
  abyssian(367, 'Bloodmoon Priestess', 4, 'Minion', 'rare', 'f4_bloodmoon'),
  abyssian(20463, 'Breath Of The Unborn', 4, 'Spell', 'common', 'icon_f4_d2_breathoftheunborn'),
  abyssian(20468, 'Dark Seed', 4, 'Spell', 'rare', 'icon_f4_d2_darkseed'),
  abyssian(20459, 'Nether Summoning', 4, 'Spell', 'legendary', 'icon_f4_d2_nethersummoning'),
  abyssian(378, 'Black Solus', 5, 'Minion', 'epic', 'f4_blacksolus'),
  abyssian(20467, 'Dark Terminus', 5, 'Spell', 'basic', 'icon_f4_d2_darktransformation'),
  abyssian(379, 'Reaper of the Nine Moons', 5, 'Minion', 'epic', 'f4_reaperninemoons'),
  abyssian(375, 'Shadowdancer', 5, 'Minion', 'rare', 'f4_shadowdancer'),
  abyssian(371, 'Vorpal Reaver', 6, 'Minion', 'legendary', 'f4_daemongate'),
  abyssian(20460, 'Shadow Nova', 7, 'Spell', 'basic', 'icon_f4_d2_shadownova'),
  abyssian(377, 'Spectral Revenant', 7, 'Minion', 'legendary', 'f4_daemonvoid'),
]

export const magmarCardData: ScrapedCard[] = [
  magmar(477, 'Ragnora the Relentless', 0, 'General', 'basic', 'f5_3rdgeneral'),
  magmar(476, 'Starhorn the Seeker', 0, 'General', 'basic', 'f5_altgeneral'),
  magmar(459, 'Vaath the Immortal', 0, 'General', 'basic', 'f5_general'),
  magmar(20483, 'Amplification', 0, 'Spell', 'common', 'icon_f5_d2_amplification'),
  magmar(20475, 'Dampening Wave', 0, 'Spell', 'basic', 'icon_f5_d2_dampeningwave'),
  magmar(20476, 'Flash Reincarnation', 0, 'Spell', 'rare', 'icon_f5_d2_flashreincarnation'),
  magmar(20480, 'Greater Fortitude', 1, 'Spell', 'basic', 'icon_f5_d2_greaterfortitude'),
  magmar(30115, 'Iridium Scale', 1, 'Artifact', 'epic', 'artifact_f5_d2_irridiumscale'),
  magmar(20479, 'Mana Burn', 1, 'Spell', 'basic', 'icon_f5_d2_manaburn'),
  magmar(20477, 'Diretide Frenzy', 2, 'Spell', 'common', 'icon_f5_d2_diretidefrenzy'),
  magmar(467, 'Kujata', 2, 'Minion', 'epic', 'f5_kujata'),
  magmar(20488, 'Mind Steal', 2, 'Spell', 'epic', 'icon_f5_d2_mindsteal'),
  magmar(20487, 'Natural Selection', 2, 'Spell', 'basic', 'icon_f5_d2_naturalselection'),
  magmar(20478, 'Tremor', 2, 'Spell', 'common', 'icon_f5_d2_tremor'),
  magmar(470, 'Young Silithar', 2, 'Minion', 'common', 'f5_silitharyoung'),
  magmar(20486, 'Chrysalis Burst', 3, 'Spell', 'legendary', 'icon_f5_d2_chrysalisburn'),
  magmar(460, 'Earth Walker', 3, 'Minion', 'basic', 'f5_earthwalker'),
  magmar(20490, 'Kinetic Equilibrium', 3, 'Spell', 'rare', 'icon_f5_d2_kineticequilibrium'),
  magmar(464, 'Phalanxar', 3, 'Minion', 'basic', 'f5_tank'),
  magmar(468, 'Primordial Gazer', 3, 'Minion', 'basic', 'f5_primordialgazer'),
  magmar(30114, 'Twin Fang', 3, 'Artifact', 'legendary', 'artifact_f5_d2_twinfang'),
  magmar(475, 'Vindicator', 3, 'Minion', 'legendary', 'f5_vindicator'),
  magmar(30113, 'Adamantite Claws', 4, 'Artifact', 'basic', 'artifact_f5_d2_adamantineclaws'),
  magmar(20481, 'Earth Sphere', 4, 'Spell', 'common', 'icon_f5_d2_earthsphere'),
  magmar(20489, 'Egg Morph', 4, 'Spell', 'rare', 'icon_f5_d2_eggmorph'),
  magmar(465, 'Elucidator', 4, 'Minion', 'rare', 'f5_support'),
  magmar(461, 'Grimrock', 4, 'Minion', 'common', 'f5_grimrock'),
  magmar(471, 'Veteran Silithar', 4, 'Minion', 'common', 'f5_silitharveteran'),
  magmar(462, 'Kolossus', 5, 'Minion', 'common', 'f5_kolossus'),
  magmar(20484, 'Metamorphosis', 5, 'Spell', 'legendary', 'icon_f5_d2_metamorphosis'),
  magmar(20485, 'Plasma Storm', 5, 'Spell', 'basic', 'icon_f5_d2_plasmastorm'),
  magmar(473, 'Spirit Harvester', 5, 'Minion', 'rare', 'f5_spiritharvester'),
  magmar(20474, 'Fractal Replication', 6, 'Spell', 'epic', 'icon_f5_d2_fractalreplication'),
  magmar(463, 'Makantor Warbeast', 6, 'Minion', 'epic', 'f5_mankatorwarbeast'),
  magmar(20482, 'Bounded Lifeforce', 7, 'Spell', 'epic', 'icon_f5_d2_boundedlifeforce'),
  magmar(472, 'Silithar Elder', 7, 'Minion', 'legendary', 'f5_silitharelder'),
  magmar(466, 'Unstable Leviathan', 7, 'Minion', 'rare', 'f5_unstableleviathan'),
]

export const vanarCardData: ScrapedCard[] = [
  vanar(568, 'Faie Bloodwing', 0, 'General', 'basic', 'f6_general'),
  vanar(594, 'Ilena Cryobyte', 0, 'General', 'basic', 'f6_3rdgeneral'),
  vanar(593, 'Kara Winterblade', 0, 'General', 'basic', 'f6_altgeneral'),
  vanar(20495, 'Flash Freeze', 0, 'Spell', 'basic', 'icon_f6_d2_flashfreeze'),
  vanar(20504, 'Polarity', 0, 'Spell', 'common', 'icon_f6_d2_polarity'),
  vanar(20501, 'Aspect of the Fox', 1, 'Spell', 'basic', 'icon_f6_d2_aspectofthefox'),
  vanar(20499, 'Mesmerize', 1, 'Spell', 'rare', 'icon_f6_d2_mesmerize'),
  vanar(576, 'Snow Chaser', 1, 'Minion', 'rare', 'f6_snowchaser'),
  vanar(30118, 'Winterblade', 1, 'Artifact', 'epic', 'artifact_f6_d2_winterblade'),
  vanar(20491, 'Bonechill Barrier', 2, 'Spell', 'common', 'icon_f6_d2_bonechillbarrier'),
  vanar(578, 'Borean Bear', 2, 'Minion', 'common', 'f6_waterbear'),
  vanar(20498, 'Boundless Courage', 2, 'Spell', 'epic', 'icon_f6_d2_unstoppableforce'),
  vanar(20494, 'Chromatic Cold', 2, 'Spell', 'basic', 'icon_f6_d2_chromaticcold'),
  vanar(30117, 'Coldbiter', 2, 'Artifact', 'legendary', 'artifact_f6_d2_frostbiter'),
  vanar(571, 'Crystal Cloaker', 2, 'Minion', 'basic', 'f6_crystalbeetle'),
  vanar(572, 'Crystal Wisp', 2, 'Minion', 'common', 'neutral_monstercrystalwisp'),
  vanar(20496, 'Frostfire', 2, 'Spell', 'basic', 'icon_f6_d2_frostfire'),
  vanar(20505, 'Hailstone Prison', 2, 'Spell', 'common', 'icon_f6_d2_hailstoneprison'),
  vanar(583, 'Hearth-Sister', 2, 'Minion', 'common', 'f6_justice'),
  vanar(20500, 'Mark of Solitude', 2, 'Spell', 'rare', 'icon_f6_d2_markofsolitude'),
  vanar(20493, 'Blazing Spines', 3, 'Spell', 'rare', 'icon_f6_d2_blazingspines'),
  vanar(20507, 'Cryogenesis', 3, 'Spell', 'common', 'icon_f6_d2_cryogenesis'),
  vanar(569, 'Fenrir Warmaster', 3, 'Minion', 'basic', 'f6_fenrirwarmaster'),
  vanar(585, 'Glacial Elemental', 3, 'Minion', 'rare', 'f6_snowman'),
  vanar(20492, 'Gravity Well', 3, 'Spell', 'legendary', 'icon_f6_d2_gravitywell'),
  vanar(30116, 'Snowpiercer', 3, 'Artifact', 'basic', 'artifact_f6_d2_snowpiercer'),
  vanar(577, 'Wolfraven', 3, 'Minion', 'common', 'f6_wolfraven'),
  vanar(20502, 'Aspect of the Wyrm', 4, 'Spell', 'epic', 'icon_f6_d2_aspectofthedrake'),
  vanar(20497, 'Avalanche', 4, 'Spell', 'basic', 'icon_f6_d2_avalanche'),
  vanar(579, 'Razorback', 4, 'Minion', 'rare', 'f6_sentinel'),
  vanar(20506, 'Spirit of the Wild', 4, 'Spell', 'epic', 'icon_f6_d2_spiritofthewild'),
  vanar(581, 'Voice of the Wind', 4, 'Minion', 'legendary', 'f6_voiceofthewind'),
  vanar(592, 'Arctic Displacer', 5, 'Minion', 'basic', 'f6_snowwyvern'),
  vanar(573, 'Frosthorn Rhyno', 5, 'Minion', 'epic', 'f6_arcticrhyno'),
  vanar(
    20503,
    'Aspect of the Mountains',
    6,
    'Spell',
    'legendary',
    'icon_f6_d2_aspectofthemountains',
  ),
  vanar(574, 'Draugar Lord', 6, 'Minion', 'epic', 'f6_draugarlord'),
  vanar(580, 'Ancient Grove', 7, 'Minion', 'legendary', 'f6_treant'),
]

export const neutralCardData: ScrapedCard[] = [
  neutral(11160, 'Dragonlark', 1, 'Minion', 'basic', 'neutral_monsterdragonhawk'),
  neutral(11185, 'Helm of MECHAZ0R', 1, 'Minion', 'common', 'neutral_mechaz0rhelm'),
  neutral(11167, 'Komodo Scavenger', 1, 'Minion', 'basic', 'neutral_beastcavern'),
  neutral(11243, 'Maw', 1, 'Minion', 'common', 'neutral_maw'),
  neutral(11252, 'Moebius', 1, 'Minion', 'epic', 'neutral_moebius'),
  neutral(11168, 'Planar Scout', 1, 'Minion', 'basic', 'neutral_beastphasehound'),
  neutral(11272, 'Prophet of the White Palm', 1, 'Minion', 'rare', 'neutral_prophetwhitepalm'),
  neutral(11191, 'Swamp Entangler', 1, 'Minion', 'common', 'neutral_beastswamp'),
  neutral(11257, 'Aethermaster', 2, 'Minion', 'epic', 'neutral_aethermaster'),
  neutral(11273, 'Araki Headhunter', 2, 'Minion', 'epic', 'neutral_arakiheadhunter'),
  neutral(11215, 'Azure Horn Shaman', 2, 'Minion', 'rare', 'neutral_mercazurehorn'),
  neutral(11217, 'Bloodtear Alchemist', 2, 'Minion', 'basic', 'neutral_bloodstonealchemist'),
  neutral(11195, 'Bluetip Scorpion', 2, 'Minion', 'common', 'neutral_monsteronyxscorpion'),
  neutral(11218, 'Crossbones', 2, 'Minion', 'rare', 'neutral_golem_crossbones'),
  neutral(11278, 'Dreamgazer', 2, 'Minion', 'epic', 'neutral_dreamgazer'),
  neutral(11169, 'Ephemeral Shroud', 2, 'Minion', 'basic', 'neutral_monsterdreamoracle'),
  neutral(11216, 'Flameblood Warlock', 2, 'Minion', 'rare', 'neutral_mercflamebloodwarlock'),
  neutral(11265, 'Ghost Lynx', 2, 'Minion', 'common', 'neutral_ghostlynx'),
  neutral(11204, 'Golem Metallurgist', 2, 'Minion', 'rare', 'neutral_golemsteel'),
  neutral(11245, 'Healing Mystic', 2, 'Minion', 'basic', 'neutral_healingmystic'),
  neutral(11270, 'Jaxi', 2, 'Minion', 'common', 'neutral_jaxi'),
  neutral(11177, 'Manaforger', 2, 'Minion', 'rare', 'neutral_monsterartifacthunter'),
  neutral(11206, 'Piercing Mantis', 2, 'Minion', 'basic', 'neutral_monstershreddingmantis'),
  neutral(11203, 'Primus Fist', 2, 'Minion', 'common', 'neutral_gauntletmaster'),
  neutral(11192, 'Rock Pulverizer', 2, 'Minion', 'basic', 'neutral_monsterexplodingdemon'),
  neutral(11222, 'Rust Crawler', 2, 'Minion', 'common', 'neutral_monstercoiledcrawler'),
  neutral(11161, 'Silvertongue Corsair', 2, 'Minion', 'rare', 'neutral_mercpirate'),
  neutral(11213, 'Skyrock Golem', 2, 'Minion', 'basic', 'neutral_golemrunesand'),
  neutral(11170, 'Vale Hunter', 2, 'Minion', 'basic', 'neutral_tribalranged1'),
  neutral(11186, 'Wings of MECHAZ0R', 2, 'Minion', 'common', 'neutral_mechaz0rwing'),
  neutral(11179, 'Alcuin Loremaster', 3, 'Minion', 'epic', 'neutral_mercsightlessfarseer'),
  neutral(11163, 'Blaze Hound', 3, 'Minion', 'common', 'neutral_beastdarkharbinger'),
  neutral(11173, 'Bloodshard Golem', 3, 'Minion', 'basic', 'neutral_golembloodshard'),
  neutral(11187, 'Cannon of MECHAZ0R', 3, 'Minion', 'rare', 'neutral_mechaz0rcannon'),
  neutral(11227, 'Chaos Elemental', 3, 'Minion', 'epic', 'neutral_chaoselemental'),
  neutral(11196, 'Crimson Oculus', 3, 'Minion', 'rare', 'neutral_monsteroculus'),
  neutral(11166, 'Fire Spitter', 3, 'Minion', 'basic', 'neutral_mercgrenadier'),
  neutral(11205, 'Golem Vanguard', 3, 'Minion', 'legendary', 'neutral_golemstone'),
  neutral(11251, 'Lady Locke', 3, 'Minion', 'legendary', 'neutral_ladylocke'),
  neutral(11212, 'Mirkblood Devourer', 3, 'Minion', 'legendary', 'neutral_beastmirkwooddevourer'),
  neutral(11264, 'Mogwai', 3, 'Minion', 'epic', 'neutral_mogwai'),
  neutral(11178, 'Prismatic Illusionist', 3, 'Minion', 'rare', 'neutral_prismaticillusionist'),
  neutral(11199, 'Putrid Dreadflayer', 3, 'Minion', 'basic', 'neutral_monsterputridmindflayer'),
  neutral(11165, 'Repulsor Beast', 3, 'Minion', 'basic', 'neutral_beastrepulsion'),
  neutral(11162, 'Saberspine Tiger', 3, 'Minion', 'basic', 'neutral_beastsaberspinetiger'),
  neutral(11164, 'Sand Burrower', 3, 'Minion', 'common', 'neutral_monsterblacksandburrower'),
  neutral(11210, 'Sarlac the Eternal', 3, 'Minion', 'legendary', 'f1_sunstonemaiden'),
  neutral(11190, 'Shield Oracle', 3, 'Minion', 'common', 'neutral_mercshieldoracle'),
  neutral(11214, 'Sojourner', 3, 'Minion', 'rare', 'neutral_mercgambitgirl'),
  neutral(11239, 'Spelljammer', 3, 'Minion', 'legendary', 'neutral_spelljammer'),
  neutral(11176, 'Sun Seer', 3, 'Minion', 'common', 'neutral_mercsunseer'),
  neutral(11188, 'Sword of MECHAZ0R', 3, 'Minion', 'rare', 'neutral_mechaz0rsword'),
  neutral(11219, 'Sworn Avenger', 3, 'Minion', 'epic', 'neutral_mercswornavanger'),
  neutral(11238, 'Syvrel the Exile', 3, 'Minion', 'epic', 'neutral_syvrel'),
  neutral(11225, 'Venom Toth', 3, 'Minion', 'epic', 'neutral_merctwinbladewarmonger'),
  neutral(11246, 'Void Hunter', 3, 'Minion', 'common', 'neutral_voidhunter'),
  neutral(11263, 'Wind Runner', 3, 'Minion', 'rare', 'neutral_windrunner'),
  neutral(11276, 'Wings of Paradise', 3, 'Minion', 'common', 'neutral_wingsofparadise'),
  neutral(11226, 'Artifact Hunter', 4, 'Minion', 'epic', 'neutral_windstopper'),
  neutral(11262, 'Black Locust', 4, 'Minion', 'legendary', 'neutral_blacklocust'),
  neutral(11253, 'Captain Hank Hart', 4, 'Minion', 'epic', 'neutral_captainhankheart'),
  neutral(11189, 'Chassis of MECHAZ0R', 4, 'Minion', 'epic', 'neutral_mechaz0rchassis'),
  neutral(11194, 'Cinderbeast', 4, 'Minion', 'common', 'neutral_monsterdarkharbinger'),
  neutral(11240, 'Dioltas', 4, 'Minion', 'epic', 'neutral_dilotas_attack'),
  neutral(11259, 'Emerald Rejuvenator', 4, 'Minion', 'rare', 'neutral_rejuvenator'),
  neutral(11207, 'Frostbone Naga', 4, 'Minion', 'common', 'neutral_mercfrostbonenaga'),
  neutral(11242, 'Hailstone Golem', 4, 'Minion', 'basic', 'neutral_golemice'),
  neutral(11280, 'Hollow Grovekeeper', 4, 'Minion', 'legendary', 'neutral_hollowgrovekeeper'),
  neutral(11274, 'Keeper of the Vale', 4, 'Minion', 'legendary', 'neutral_keeperofthevale'),
  neutral(11181, 'Lightbender', 4, 'Minion', 'rare', 'neutral_mercarcanelimiter'),
  neutral(11229, 'Mindwarper', 4, 'Minion', 'rare', 'neutral_mercmindwarper'),
  neutral(11180, 'Owlbeast Sage', 4, 'Minion', 'rare', 'neutral_mercowlbearmage'),
  neutral(11193, 'Primus Shieldmaster', 4, 'Minion', 'basic', 'neutral_primusshieldmaster'),
  neutral(11255, 'Purgatos, the Realmkeeper', 4, 'Minion', 'epic', 'neutral_purgatos'),
  neutral(11209, 'Silhouette Tracer', 4, 'Minion', 'common', 'neutral_silhouettetracer'),
  neutral(11256, 'Songweaver', 4, 'Minion', 'common', 'neutral_mercsongweaver'),
  neutral(11271, 'Sun Elemental', 4, 'Minion', 'common', 'neutral_sunelemental'),
  neutral(11281, 'Tethermancer', 4, 'Minion', 'rare', 'neutral_d2_tethermancer'),
  neutral(11197, 'Thorn Needler', 4, 'Minion', 'basic', 'neutral_mercneedler'),
  neutral(11275, 'White Widow', 4, 'Minion', 'rare', 'neutral_whitewidow'),
  neutral(11200, 'Young Flamewing', 4, 'Minion', 'basic', 'neutral_monsterflamewing'),
  neutral(11247, 'Ash Mephyt', 5, 'Minion', 'common', 'neutral_ashmephyt'),
  neutral(11172, 'Brightmoss Golem', 5, 'Minion', 'basic', 'neutral_golemnature'),
  neutral(11223, 'Dagger Kiri', 5, 'Minion', 'common', 'neutral_mercdaggerkiri'),
  neutral(11224, 'Dancing Blades', 5, 'Minion', 'common', 'neutral_monsterdancingblades'),
  neutral(11267, 'Flame Acolyte', 5, 'Minion', 'rare', 'neutral_firestarter'),
  neutral(11237, 'Lux Ignis', 5, 'Minion', 'epic', 'neutral_luxignis'),
  neutral(11198, 'Rogue Warden', 5, 'Minion', 'basic', 'f1_ranged'),
  neutral(11220, 'Sworn Defender', 5, 'Minion', 'epic', 'neutral_mercsworndefender'),
  neutral(11249, 'The High Hand', 5, 'Minion', 'common', 'neutral_highhand'),
  neutral(11171, 'Twilight Sorcerer', 5, 'Minion', 'epic', 'neutral_merctwilightmage'),
  neutral(11258, "Zen'Rui, the Blightspawned", 5, 'Minion', 'legendary', 'neutral_zenrui'),
  neutral(11208, 'Archon Spellbinder', 6, 'Minion', 'legendary', 'neutral_mercarchonspellbinder'),
  neutral(11279, 'Bonereaper', 6, 'Minion', 'epic', 'neutral_bonereaper'),
  neutral(11244, 'Deathblighter', 6, 'Minion', 'common', 'neutral_deathblighter'),
  neutral(11250, 'Eclipse', 6, 'Minion', 'legendary', 'neutral_eclipse'),
  neutral(11248, 'First Sword of Akrane', 6, 'Minion', 'common', 'neutral_swordofakrane'),
  neutral(11228, 'Jax Truesight', 6, 'Minion', 'legendary', 'neutral_jaxtruesight'),
  neutral(11182, 'Serpenti', 6, 'Minion', 'common', 'neutral_serpenti'),
  neutral(11201, 'Storm Aratha', 6, 'Minion', 'basic', 'neutral_monsterlightningbeetle'),
  neutral(11175, 'Stormmetal Golem', 6, 'Minion', 'basic', 'neutral_golemstormmetal'),
  neutral(11277, 'Astral Crusader', 7, 'Minion', 'legendary', 'neutral_astralcrusader'),
  neutral(11211, 'Dark Nemesis', 7, 'Minion', 'legendary', 'neutral_darknemesis'),
  neutral(11174, 'Dragonbone Golem', 7, 'Minion', 'basic', 'neutral_golemdragonbone'),
  neutral(11266, 'Grailmaster', 7, 'Minion', 'epic', 'neutral_spiritscribe'),
  neutral(11261, 'Paddo', 7, 'Minion', 'legendary', 'neutral_paddo'),
  neutral(11230, 'Pandora', 7, 'Minion', 'legendary', 'neutral_pandora'),
  neutral(11221, 'Red Synja', 7, 'Minion', 'legendary', 'neutral_monsterredsynja'),
  neutral(11254, 'Rook', 7, 'Minion', 'legendary', 'neutral_rook'),
  neutral(11282, 'War Talon', 7, 'Minion', 'common', 'neutral_wartalon'),
  neutral(11202, 'Whistling Blade', 7, 'Minion', 'common', 'neutral_monsterwhistlingblade'),
  neutral(11269, 'Khymera', 8, 'Minion', 'legendary', 'neutral_khymera'),
  neutral(11260, 'Zurael, the Lifegiver', 9, 'Minion', 'legendary', 'neutral_zurael'),
]

const scrapedCards = [
  ...lyonarCardData,
  ...songhaiCardData,
  ...vetruvianCardData,
  ...abyssianCardData,
  ...magmarCardData,
  ...vanarCardData,
  ...neutralCardData,
]

export const scrapedCardsById = scrapedCards.reduce(
  (acc, cardData) => ({
    ...acc,
    [cardData.id]: cardData,
  }),
  {} as Record<number, ScrapedCard>,
)
